# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ys/Files/GitHub/DBMS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ys/Files/GitHub/DBMS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ys/Files/GitHub/DBMS/CMakeFiles /Users/ys/Files/GitHub/DBMS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ys/Files/GitHub/DBMS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DBMS

# Build rule for target.
DBMS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DBMS
.PHONY : DBMS

# fast build rule for target.
DBMS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/build
.PHONY : DBMS/fast

#=============================================================================
# Target rules for targets named bpt

# Build rule for target.
bpt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bpt
.PHONY : bpt

# fast build rule for target.
bpt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/build
.PHONY : bpt/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/main.cpp.s
.PHONY : main.cpp.s

src/Api.o: src/Api.cpp.o
.PHONY : src/Api.o

# target to build an object file
src/Api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/Api.cpp.o
.PHONY : src/Api.cpp.o

src/Api.i: src/Api.cpp.i
.PHONY : src/Api.i

# target to preprocess a source file
src/Api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/Api.cpp.i
.PHONY : src/Api.cpp.i

src/Api.s: src/Api.cpp.s
.PHONY : src/Api.s

# target to generate assembly for a file
src/Api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/Api.cpp.s
.PHONY : src/Api.cpp.s

src/BufferLayer.o: src/BufferLayer.cpp.o
.PHONY : src/BufferLayer.o

# target to build an object file
src/BufferLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/BufferLayer.cpp.o
.PHONY : src/BufferLayer.cpp.o

src/BufferLayer.i: src/BufferLayer.cpp.i
.PHONY : src/BufferLayer.i

# target to preprocess a source file
src/BufferLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/BufferLayer.cpp.i
.PHONY : src/BufferLayer.cpp.i

src/BufferLayer.s: src/BufferLayer.cpp.s
.PHONY : src/BufferLayer.s

# target to generate assembly for a file
src/BufferLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/BufferLayer.cpp.s
.PHONY : src/BufferLayer.cpp.s

src/DiskLayer.o: src/DiskLayer.cpp.o
.PHONY : src/DiskLayer.o

# target to build an object file
src/DiskLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/DiskLayer.cpp.o
.PHONY : src/DiskLayer.cpp.o

src/DiskLayer.i: src/DiskLayer.cpp.i
.PHONY : src/DiskLayer.i

# target to preprocess a source file
src/DiskLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/DiskLayer.cpp.i
.PHONY : src/DiskLayer.cpp.i

src/DiskLayer.s: src/DiskLayer.cpp.s
.PHONY : src/DiskLayer.s

# target to generate assembly for a file
src/DiskLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/DiskLayer.cpp.s
.PHONY : src/DiskLayer.cpp.s

src/IndexLayer.o: src/IndexLayer.cpp.o
.PHONY : src/IndexLayer.o

# target to build an object file
src/IndexLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/IndexLayer.cpp.o
.PHONY : src/IndexLayer.cpp.o

src/IndexLayer.i: src/IndexLayer.cpp.i
.PHONY : src/IndexLayer.i

# target to preprocess a source file
src/IndexLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/IndexLayer.cpp.i
.PHONY : src/IndexLayer.cpp.i

src/IndexLayer.s: src/IndexLayer.cpp.s
.PHONY : src/IndexLayer.s

# target to generate assembly for a file
src/IndexLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/IndexLayer.cpp.s
.PHONY : src/IndexLayer.cpp.s

src/LockLayer.o: src/LockLayer.cpp.o
.PHONY : src/LockLayer.o

# target to build an object file
src/LockLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LockLayer.cpp.o
.PHONY : src/LockLayer.cpp.o

src/LockLayer.i: src/LockLayer.cpp.i
.PHONY : src/LockLayer.i

# target to preprocess a source file
src/LockLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LockLayer.cpp.i
.PHONY : src/LockLayer.cpp.i

src/LockLayer.s: src/LockLayer.cpp.s
.PHONY : src/LockLayer.s

# target to generate assembly for a file
src/LockLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LockLayer.cpp.s
.PHONY : src/LockLayer.cpp.s

src/LogLayer.o: src/LogLayer.cpp.o
.PHONY : src/LogLayer.o

# target to build an object file
src/LogLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LogLayer.cpp.o
.PHONY : src/LogLayer.cpp.o

src/LogLayer.i: src/LogLayer.cpp.i
.PHONY : src/LogLayer.i

# target to preprocess a source file
src/LogLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LogLayer.cpp.i
.PHONY : src/LogLayer.cpp.i

src/LogLayer.s: src/LogLayer.cpp.s
.PHONY : src/LogLayer.s

# target to generate assembly for a file
src/LogLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/LogLayer.cpp.s
.PHONY : src/LogLayer.cpp.s

src/TransactionLayer.o: src/TransactionLayer.cpp.o
.PHONY : src/TransactionLayer.o

# target to build an object file
src/TransactionLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/TransactionLayer.cpp.o
.PHONY : src/TransactionLayer.cpp.o

src/TransactionLayer.i: src/TransactionLayer.cpp.i
.PHONY : src/TransactionLayer.i

# target to preprocess a source file
src/TransactionLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/TransactionLayer.cpp.i
.PHONY : src/TransactionLayer.cpp.i

src/TransactionLayer.s: src/TransactionLayer.cpp.s
.PHONY : src/TransactionLayer.s

# target to generate assembly for a file
src/TransactionLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpt.dir/build.make CMakeFiles/bpt.dir/src/TransactionLayer.cpp.s
.PHONY : src/TransactionLayer.cpp.s

src/test/DeadlockTest.o: src/test/DeadlockTest.cpp.o
.PHONY : src/test/DeadlockTest.o

# target to build an object file
src/test/DeadlockTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/DeadlockTest.cpp.o
.PHONY : src/test/DeadlockTest.cpp.o

src/test/DeadlockTest.i: src/test/DeadlockTest.cpp.i
.PHONY : src/test/DeadlockTest.i

# target to preprocess a source file
src/test/DeadlockTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/DeadlockTest.cpp.i
.PHONY : src/test/DeadlockTest.cpp.i

src/test/DeadlockTest.s: src/test/DeadlockTest.cpp.s
.PHONY : src/test/DeadlockTest.s

# target to generate assembly for a file
src/test/DeadlockTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/DeadlockTest.cpp.s
.PHONY : src/test/DeadlockTest.cpp.s

src/test/ExclusiveLockTest.o: src/test/ExclusiveLockTest.cpp.o
.PHONY : src/test/ExclusiveLockTest.o

# target to build an object file
src/test/ExclusiveLockTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/ExclusiveLockTest.cpp.o
.PHONY : src/test/ExclusiveLockTest.cpp.o

src/test/ExclusiveLockTest.i: src/test/ExclusiveLockTest.cpp.i
.PHONY : src/test/ExclusiveLockTest.i

# target to preprocess a source file
src/test/ExclusiveLockTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/ExclusiveLockTest.cpp.i
.PHONY : src/test/ExclusiveLockTest.cpp.i

src/test/ExclusiveLockTest.s: src/test/ExclusiveLockTest.cpp.s
.PHONY : src/test/ExclusiveLockTest.s

# target to generate assembly for a file
src/test/ExclusiveLockTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/ExclusiveLockTest.cpp.s
.PHONY : src/test/ExclusiveLockTest.cpp.s

src/test/MixedLockTest.o: src/test/MixedLockTest.cpp.o
.PHONY : src/test/MixedLockTest.o

# target to build an object file
src/test/MixedLockTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/MixedLockTest.cpp.o
.PHONY : src/test/MixedLockTest.cpp.o

src/test/MixedLockTest.i: src/test/MixedLockTest.cpp.i
.PHONY : src/test/MixedLockTest.i

# target to preprocess a source file
src/test/MixedLockTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/MixedLockTest.cpp.i
.PHONY : src/test/MixedLockTest.cpp.i

src/test/MixedLockTest.s: src/test/MixedLockTest.cpp.s
.PHONY : src/test/MixedLockTest.s

# target to generate assembly for a file
src/test/MixedLockTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/MixedLockTest.cpp.s
.PHONY : src/test/MixedLockTest.cpp.s

src/test/SharedLockTest.o: src/test/SharedLockTest.cpp.o
.PHONY : src/test/SharedLockTest.o

# target to build an object file
src/test/SharedLockTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SharedLockTest.cpp.o
.PHONY : src/test/SharedLockTest.cpp.o

src/test/SharedLockTest.i: src/test/SharedLockTest.cpp.i
.PHONY : src/test/SharedLockTest.i

# target to preprocess a source file
src/test/SharedLockTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SharedLockTest.cpp.i
.PHONY : src/test/SharedLockTest.cpp.i

src/test/SharedLockTest.s: src/test/SharedLockTest.cpp.s
.PHONY : src/test/SharedLockTest.s

# target to generate assembly for a file
src/test/SharedLockTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SharedLockTest.cpp.s
.PHONY : src/test/SharedLockTest.cpp.s

src/test/SingleThreadTest.o: src/test/SingleThreadTest.cpp.o
.PHONY : src/test/SingleThreadTest.o

# target to build an object file
src/test/SingleThreadTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SingleThreadTest.cpp.o
.PHONY : src/test/SingleThreadTest.cpp.o

src/test/SingleThreadTest.i: src/test/SingleThreadTest.cpp.i
.PHONY : src/test/SingleThreadTest.i

# target to preprocess a source file
src/test/SingleThreadTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SingleThreadTest.cpp.i
.PHONY : src/test/SingleThreadTest.cpp.i

src/test/SingleThreadTest.s: src/test/SingleThreadTest.cpp.s
.PHONY : src/test/SingleThreadTest.s

# target to generate assembly for a file
src/test/SingleThreadTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/SingleThreadTest.cpp.s
.PHONY : src/test/SingleThreadTest.cpp.s

src/test/TestUtils.o: src/test/TestUtils.cpp.o
.PHONY : src/test/TestUtils.o

# target to build an object file
src/test/TestUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/TestUtils.cpp.o
.PHONY : src/test/TestUtils.cpp.o

src/test/TestUtils.i: src/test/TestUtils.cpp.i
.PHONY : src/test/TestUtils.i

# target to preprocess a source file
src/test/TestUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/TestUtils.cpp.i
.PHONY : src/test/TestUtils.cpp.i

src/test/TestUtils.s: src/test/TestUtils.cpp.s
.PHONY : src/test/TestUtils.s

# target to generate assembly for a file
src/test/TestUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBMS.dir/build.make CMakeFiles/DBMS.dir/src/test/TestUtils.cpp.s
.PHONY : src/test/TestUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DBMS"
	@echo "... bpt"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Api.o"
	@echo "... src/Api.i"
	@echo "... src/Api.s"
	@echo "... src/BufferLayer.o"
	@echo "... src/BufferLayer.i"
	@echo "... src/BufferLayer.s"
	@echo "... src/DiskLayer.o"
	@echo "... src/DiskLayer.i"
	@echo "... src/DiskLayer.s"
	@echo "... src/IndexLayer.o"
	@echo "... src/IndexLayer.i"
	@echo "... src/IndexLayer.s"
	@echo "... src/LockLayer.o"
	@echo "... src/LockLayer.i"
	@echo "... src/LockLayer.s"
	@echo "... src/LogLayer.o"
	@echo "... src/LogLayer.i"
	@echo "... src/LogLayer.s"
	@echo "... src/TransactionLayer.o"
	@echo "... src/TransactionLayer.i"
	@echo "... src/TransactionLayer.s"
	@echo "... src/test/DeadlockTest.o"
	@echo "... src/test/DeadlockTest.i"
	@echo "... src/test/DeadlockTest.s"
	@echo "... src/test/ExclusiveLockTest.o"
	@echo "... src/test/ExclusiveLockTest.i"
	@echo "... src/test/ExclusiveLockTest.s"
	@echo "... src/test/MixedLockTest.o"
	@echo "... src/test/MixedLockTest.i"
	@echo "... src/test/MixedLockTest.s"
	@echo "... src/test/SharedLockTest.o"
	@echo "... src/test/SharedLockTest.i"
	@echo "... src/test/SharedLockTest.s"
	@echo "... src/test/SingleThreadTest.o"
	@echo "... src/test/SingleThreadTest.i"
	@echo "... src/test/SingleThreadTest.s"
	@echo "... src/test/TestUtils.o"
	@echo "... src/test/TestUtils.i"
	@echo "... src/test/TestUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

